---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    http_servers:
      hosts:
        iso-server:
          ansible_host: "{{ vault_http_server_ip }}"
          ansible_user: "{{ vault_http_server_user }}"

    hub_nodes:
      hosts:
        hub-node1:
          ansible_host: "{{ hostvars['hub-node1']['node']['ipv4_address'] }}"
        hub-node2:
          ansible_host: "{{ hostvars['hub-node2']['node']['ipv4_address'] }}"
        hub-node3:
          ansible_host: "{{ hostvars['hub-node3']['node']['ipv4_address'] }}"
